---
pagetitle: Juhyun Bae
---

<link rel="stylesheet" href="styles.css" type="text/css">

$^*$ Graduate Student Coauthor

------

### Peer-reviewed Publications

* Hong, I.,& __Bae, J.__,& Choi, YJ. (Forthcoming). “The Unlikely Rise of Basic Income from Agenda Universe to Decision Agenda: How Policy Entrepreneurs Navigate Institutions.” _Journal of Asian Public Policy_, [<a href = "files/BImanuscript.pdf" target="_blank">Manuscript</a>]

* __Bae, J.__, & Choi, YJ. (2017). "Causes and Consequences of Hanjin Shipping Bankruptcy: Dilemma of Developmental Liberalist Regime in Industrial Restructuring." _Journal of Governmental Studies_, 23(3), 193-227.[<a href = "https://kiss.kstudy.com/Detail/Ar?key=3568681" target="_blank">Journal Article</a>]

* Choi, YJ., & __Bae, J.__ (2016). "Designing Future Social Security: Critical Review of Mid- to Long-term Social Security Planning." _Korean Social Security Studies_, 32(2), 271-299.[<a href = "https://kiss.kstudy.com/Detail/Ar?key=3460208" target="_blank">Journal Article</a>]
  
------

### Working Papers

* __Bae, J.__ (Under Review). “American Public Opinion Toward Gig Workers’ Welfare Deservingness: Evidence from Survey Experiment.” [<a href = "files/Manuscript_Bae.pdf" target="_blank">Manuscript</a>]  [<a href = "files/Deserving_Online Appendices.pdf" target="_blank">Online Appendix</a>]

<div style="line-height:50%;"><br></div>

* __Bae, J.__ (Under Review). “The Effects of Expanded Pandemic Unemployment Assistance on Labor Market Outsiders’ Financial and Mental Wellbeing: Evidence from Staggered DID and Triple-Difference.”  [<a href = "files/UI_manuscript.pdf" target="_blank">Manuscript</a>]  [<a href = "files/Online Appendix_UI.pdf" target="_blank">Online Appendix</a>]
<details> <summary><font size=2>Abstract</font size></summary>> <div style="line-height:100%;"><font size=2> During COVID-19, for the first time in the US's history of the Unemployment Insurance (UI) system, UI benefit was expanded even to non-standard workers who ordinally would not be eligible for benefits through the general UI system. Given the non-standard workers’ high level of insecurity and exclusion from the social security system as labor market outsiders, it is meaningful to investigate the effects of the generosity of UI benefits on their economic and emotional security. To estimate it, I analyze staggered difference-in-differences and triple-difference (DDD) models using the Housing Pulse Survey (HPS) data. I found that the early termination of the pandemic UI programs increases the financial and mental difficulties, especially the labor market outsiders undergo more difficulties than the labor market insiders. The DDD results present that withdrawing the UI benefits increases the financial difficulty of paying expenses for labor market outsiders. This paper sheds light on the original findings that the expanded eligibility helps alleviate economic setbacks and mental difficulty, especially, for labor market outsiders who have been excluded from the existing social insurance system. The finding implies that the existing policy blind spot to labor market outsiders could accelerate the precarity of labor market outsiders particularly under the unexpected crisis and labor market disruptions, and policy actions to protect them should be considered. </font size></div>
</details>

<div style="line-height:50%;"><br></div>

<div style="line-height:50%;"><br></div>

* __Bae, J.__ & Jung, Y$^*$. (Under Review). “Spatial Inequality and the Role of Public Spaces: Lessons from COVID-19.”
<details><summary><font size=2>Abstract</font size></summary>> <div style="line-height:100%;"><font size=2> This study examines whether public spaces play a role in mitigating existing inequality, mainly how different types of public spaces reduce inequality particularly during the COVID-19. It is motivated by concerns that those with poor living conditions may suffer more due to limited access to public spaces during the pandemic, highlighting the potential of public spaces that extend the private spaces of the impoverished. Given that depression stems from spatial and socioeconomic backgrounds, this study uses depression as a proxy for inequality. Using survey and administrative data in South Korea, the findings indicate that accessibility to complete-public spaces such as parks and even cafés as semi-public spaces for a social mix reduce depression levels, whereas the accessibility to shopping centers as consumerism-based semi-public spaces increase depression. Given the increasing concern for future crises such as climate change, these findings suggest strategies of public spaces to mitigate spatial inequalities should be reconsidered.</font size></div></details>

<div style="line-height:50%;"><br></div>

* __Bae, J.__ & Haselswerdt, J. (Dissertation Chapter). “The Divided Welfare State and Inadequate Safety Net in the Gig Economy: Evidence from an Original Survey of American Workers.”

<div style="line-height:50%;"><br></div>

* __Bae, J.__ & Landgrave, M. (Working paper). “Does Context Matter?: Support for Administrative in Welfare Programs.”
<details> <summary><font size=2>Abstract</font size></summary>> <div style="line-height:100%;"><font size=2> Due to the onerous experience, high levels of administrative burden reduce the rate of program take-up (Herd and Moynihan, 2019). Despite their costs, both in terms of implementation and reduced program uptake, administrative burdens serve to provide program legitimacy. Existing studies find that high levels of administrative burden increase a program’s favorability, especially among Republicans (Nicholson-Crotty et al., 2022; Keiser and Miller, 2020). However, the underlying mechanism for why administrative burdens increase program favorability remains unclear. We seek to advance the literature by studying under what contexts people support higher administrative burdens and increase program favorability. We hypothesize that support for administrative burdens is context dependent and differs on how an individual construes the world using their heuristics. To our knowledge, we are among the first to study the comparative effect of different contexts on support for administrative burden. Our study not only have practical implementations for public policy implementation, but also contributes to the academic literature by helping us better understand the underlying mechanism between administrative burden and program favorability. </font size></div></details>

<div style="line-height:50%;"><br></div>

------

### Book Chapters and Other Research Reports

* Kim, EJ., Choi, IH., Sun, BY., Sung, K., __Bae, J.__, Kim, SJ., & Yang, NJ. (2018) “A Study for the Re-establishment of Sustainable Care Policy(Ⅱ)”. Seoul: Korean Women’s Development Institute. [<a href = "files/Sustainable Care Policy.pdf" target="_blank">Summary of the Research Report in English</a>]

* Kim, EJ., Choi, IH., Song, HJ., Bae, HJ., Choi, JH, __Bae, J.__, & Sung, K. (2018) “A Study on the Status of Sole-Parent Families”. Seoul: Korean Women’s Development Institute. [<a href = "https://www.kwdi.re.kr/publications/reportView.do?p=29&idx=124179" target="_blank">Link</a>]

* Choi, YJ., Jun, M$^*$, __Bae, J__, & Yoon, S$^*$ . (2018). “Ch.12. Why is Uncertainty Unequal without Government’s Precautionary Principle?: The Case of Toxic Humidifier Disinfectant.” In Moon, MJ.(eds), The Quality of Government and Life (pp.361-398).[<a href = "https://www.google.com/books/edition/%EC%A0%95%EB%B6%80_%EC%9D%98_%EC%A7%88_%EA%B3%BC_%EC%82%B6_%EC%9D%98_%EC%A7%88/r9kwwAEACAAJ?hl=en&kptab=overview" target="_blank">Link</a>]

* Choi, YJ., Jun, M$^*$, __Bae, J__, & Yoon, S$^*$ . (2017). “Ch.10. Evidence-based Policy-making in an Uncertain World: The Case of the Nuclear Power Plant in Kori, South Korea.” In Moon, MJ.(eds), Case Studies: Public Management and Public Policy (pp.257-288). [<a href = "http://dymbook.co.kr/139/?idx=842" target="_blank">Link</a>]

