---
pagetitle: Juhyun Bae
---

<link rel="stylesheet" href="styles.css" type="text/css">


### Teaching Experience
<br>

#### Graduate Instructor
* Spring 2024 __POLSC 4330: Public Policy Analysis__ _(undergraduate)_

------

#### Lab Instructor
* Fall 2023 __POLSC 3000W: Introduction to Political Research- Writing Intense__ _(undergraduate)_

------

#### Teaching Assistant
##### at the University of Missouri (Columbia, MO)
* Spring, 2023 __PA 4710/7710: The Non-Profit and Voluntary Sector__ _(undergraduate and MPA)_

* Spring, 2021 ~ Fall, 2022	__PA 8181-II: Research Methods and Inquiry in Public Affairs II__ _(MPA, online)_
  + Selected Students' Comments: 
    - Juhyun was helpful in directing me back to certain lectures when I struggled with a particular concept. She also provided encouragement and positive critique if I was off-track or not quite catching an item.
  
    - This is the best TA I have ever had. The TA was available to help me whenever I needed anything. She knew
how to breakdown complex concepts and make it easier for me to understand.
  
    - The TA was very good at helping convey where to go when I was struggling with some of the concepts in the
homework, providing great feedback on if I was close to the mark or not. Also they were very quick to reply to
emails about homework, even on the weekend with I cannot thank them enough for.

* Spring, 2021 __PA 8181-I: Research Methods and Inquiry in Public Affairs – Mid Career__ _(MPA, online)_

* Fall, 2020	__PA 8210: Public Service and Democracy__ _(MPA)_

##### at Yonsei University (Seoul, South Korea)
* Fall, 2016 & Spring, 2017 __Modern Society and Public Administration__ _(undergraduate)_

* Spring, 2016 __Comparative Public Policy__ _(undergraduate, English-only class)_

------

#### Guest Lecture
##### at the University of Missouri (Columbia, MO)
* March 2023 Topic: The Changing Labor Market and the Role of Public Policy __POLSC B4320: Public Policy__, _(asynchronous online class, undergraduate)_ <a href = "files/W2_Guest lecture_public policy_slides.pdf" target="_blank">lecture slide</a>

* Nov 2022	Topic: What are Administrative Burdens and Why Does the Government Have Them? __PA1000: Principles of Public Policy Administration__, _(undergraduate)_ <a href = "files/11.30 Adm burden_Bae_final.pdf" target="_blank">lecture slide</a>

* Oct 2022	Topic: When and How to Use Interaction Terms __PA8181-II: Research Method and Inquiry in Public Affairs__, _(online, MPA)_ <a href = "files/W5 Interaction_Ju.pdf" target="_blank">lecture slide</a>

------

#### Method Workshop Speaker

* May 2022 Topic: The Issues of TWFE Staggered DID and Stacking as the Solution, at TSGPA Women in Econometrics Group, University of Missouri <a href = "files/Stacking_05_Bae.pdf" target="_blank">lecture slide</a>

------

#### Certificate of Teaching 
* Fall 2022	Online Teaching Certificate, Office of eLearning at the University of Missouri

